export const STUDENTS = [
  {
    id: 1,
    first_name: "Dorita",
    last_name: "Glozman",
    email: "dglozman0@stumbleupon.com",
    gender: "Agender",
  },
  {
    id: 2,
    first_name: "Darrick",
    last_name: "Leedal",
    email: "dleedal1@cbsnews.com",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Shep",
    last_name: "Lincke",
    email: "slincke2@craigslist.org",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Maurise",
    last_name: "Crewes",
    email: "mcrewes3@latimes.com",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Penni",
    last_name: "Drinkhall",
    email: "pdrinkhall4@examiner.com",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Merle",
    last_name: "Tilbey",
    email: "mtilbey5@pinterest.com",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Carley",
    last_name: "Radeliffe",
    email: "cradeliffe6@wikipedia.org",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Orv",
    last_name: "Ateridge",
    email: "oateridge7@vkontakte.ru",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Filberte",
    last_name: "Piperley",
    email: "fpiperley8@webnode.com",
    gender: "Male",
  },
  {
    id: 10,
    first_name: "Laurel",
    last_name: "Wraight",
    email: "lwraight9@statcounter.com",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Garnet",
    last_name: "Tumbelty",
    email: "gtumbeltya@list-manage.com",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Giustino",
    last_name: "Junkin",
    email: "gjunkinb@wp.com",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Rafaello",
    last_name: "Karlik",
    email: "rkarlikc@huffingtonpost.com",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Tanitansy",
    last_name: "Mc Dermid",
    email: "tmcdermidd@economist.com",
    gender: "Female",
  },
  {
    id: 15,
    first_name: "Melvin",
    last_name: "Hannaby",
    email: "mhannabye@quantcast.com",
    gender: "Male",
  },
  {
    id: 16,
    first_name: "Joye",
    last_name: "Mingaye",
    email: "jmingayef@xinhuanet.com",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Gavin",
    last_name: "Lorryman",
    email: "glorrymang@theglobeandmail.com",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Claybourne",
    last_name: "Brashier",
    email: "cbrashierh@privacy.gov.au",
    gender: "Male",
  },
  {
    id: 19,
    first_name: "Catharine",
    last_name: "Cubbino",
    email: "ccubbinoi@ebay.co.uk",
    gender: "Agender",
  },
  {
    id: 20,
    first_name: "Aldous",
    last_name: "Mawtus",
    email: "amawtusj@ezinearticles.com",
    gender: "Male",
  },
  {
    id: 21,
    first_name: "Shellysheldon",
    last_name: "Dumbell",
    email: "sdumbellk@weather.com",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Fraze",
    last_name: "Hulance",
    email: "fhulancel@prnewswire.com",
    gender: "Male",
  },
  {
    id: 23,
    first_name: "Aylmer",
    last_name: "Craxford",
    email: "acraxfordm@shop-pro.jp",
    gender: "Male",
  },
  {
    id: 24,
    first_name: "Christie",
    last_name: "Bewsey",
    email: "cbewseyn@wordpress.com",
    gender: "Male",
  },
  {
    id: 25,
    first_name: "Findlay",
    last_name: "Dawtre",
    email: "fdawtreo@furl.net",
    gender: "Male",
  },
  {
    id: 26,
    first_name: "Bevan",
    last_name: "Dettmar",
    email: "bdettmarp@printfriendly.com",
    gender: "Male",
  },
  {
    id: 27,
    first_name: "Madelon",
    last_name: "Skone",
    email: "mskoneq@blog.com",
    gender: "Female",
  },
  {
    id: 28,
    first_name: "Lay",
    last_name: "Sheber",
    email: "lsheberr@fc2.com",
    gender: "Bigender",
  },
  {
    id: 29,
    first_name: "Clo",
    last_name: "L'Amie",
    email: "clamies@soup.io",
    gender: "Female",
  },
  {
    id: 30,
    first_name: "Hansiain",
    last_name: "Bore",
    email: "hboret@ibm.com",
    gender: "Male",
  },
  {
    id: 31,
    first_name: "Isabella",
    last_name: "Nerne",
    email: "inerneu@geocities.jp",
    gender: "Female",
  },
  {
    id: 32,
    first_name: "Selina",
    last_name: "Gasker",
    email: "sgaskerv@wsj.com",
    gender: "Female",
  },
  {
    id: 33,
    first_name: "Addy",
    last_name: "Lockless",
    email: "alocklessw@infoseek.co.jp",
    gender: "Male",
  },
  {
    id: 34,
    first_name: "Northrup",
    last_name: "Hambling",
    email: "nhamblingx@wikimedia.org",
    gender: "Male",
  },
  {
    id: 35,
    first_name: "Aurelia",
    last_name: "Nobriga",
    email: "anobrigay@istockphoto.com",
    gender: "Female",
  },
  {
    id: 36,
    first_name: "Paige",
    last_name: "Sibbs",
    email: "psibbsz@vinaora.com",
    gender: "Female",
  },
  {
    id: 37,
    first_name: "Kendricks",
    last_name: "Assel",
    email: "kassel10@globo.com",
    gender: "Male",
  },
  {
    id: 38,
    first_name: "Cristen",
    last_name: "Pidcock",
    email: "cpidcock11@sourceforge.net",
    gender: "Female",
  },
  {
    id: 39,
    first_name: "Tris",
    last_name: "Friese",
    email: "tfriese12@mapquest.com",
    gender: "Male",
  },
  {
    id: 40,
    first_name: "Beulah",
    last_name: "Vasiltsov",
    email: "bvasiltsov13@exblog.jp",
    gender: "Female",
  },
  {
    id: 41,
    first_name: "Linnell",
    last_name: "Le Noir",
    email: "llenoir14@nifty.com",
    gender: "Female",
  },
  {
    id: 42,
    first_name: "Giffie",
    last_name: "Havvock",
    email: "ghavvock15@drupal.org",
    gender: "Male",
  },
  {
    id: 43,
    first_name: "Zeb",
    last_name: "Frotton",
    email: "zfrotton16@php.net",
    gender: "Male",
  },
  {
    id: 44,
    first_name: "Ilsa",
    last_name: "Blomfield",
    email: "iblomfield17@simplemachines.org",
    gender: "Female",
  },
  {
    id: 45,
    first_name: "Granville",
    last_name: "Dunderdale",
    email: "gdunderdale18@wordpress.org",
    gender: "Male",
  },
  {
    id: 46,
    first_name: "Devland",
    last_name: "St. Clair",
    email: "dstclair19@nps.gov",
    gender: "Male",
  },
  {
    id: 47,
    first_name: "Roselia",
    last_name: "Ianinotti",
    email: "rianinotti1a@wordpress.com",
    gender: "Female",
  },
  {
    id: 48,
    first_name: "Ingrid",
    last_name: "Hughill",
    email: "ihughill1b@cam.ac.uk",
    gender: "Female",
  },
  {
    id: 49,
    first_name: "Kyrstin",
    last_name: "Drepp",
    email: "kdrepp1c@phoca.cz",
    gender: "Female",
  },
  {
    id: 50,
    first_name: "Morna",
    last_name: "Raynard",
    email: "mraynard1d@scientificamerican.com",
    gender: "Female",
  },
];
